prediction:
  path: /media/wlsdzyzl/DATA/vcg-results/CoW_vessel_diff/mesh/SkCNN_val_for_test
  suffix: .ply
target:
  path: /media/wlsdzyzl/DATA/datasets/pcd/CoW/output_vessel_diff_standardized/split/fold5/rmesh022
  suffix: .ply
eval_type: gen
# eval_batch_num: 2
data_form: pcd
is_mesh: true
evaluation_metrics:
    - name: meanBettiError
      min_num_faces: 100
      min_hole_size: 50