sub_dirs: [bladder, brain, colon, coronary_artery_left_d, coronary_artery_right_d, duodenum, gallbladder, liver, pancreas, skull, spleen, stomach, trachea, uterus]
target:
  path: /data/guoqingzhang/datasets/MedSDF/split/fold5/rmesh022/
  suffix: _mesh.ply
prediction:
  path: /data/guoqingzhang/meshage-results/MedSDF/gen/LDM_EDM_SkSpCNN_wo_LPC/
  suffix: .ply
eval_type: gen
data_form: pcd
is_mesh: true
evaluation_metrics:
    - name: meanBettiError
      min_num_faces: 100
      min_hole_size: 50