# train ae or vae
#### a template for pcd encoder
mode: train
model:
  # can be AE, VAE, SeM and DDPM
  name: SDF
  latent_point_constraints: True
  latent_point_inter_num: 2
  encoder:
    name: SKSDFCNN
    in_channel: 3
    out_channel: 1
    point_num: 2560
    building_block: res_dense
    projection_channel: 64
    num_neighbors_k_cross: 32
    num_neighbors_k_self: 0
    local_feature_channels: [512, 512, 512, 512]
    seq_feature_channels: [512, 512, 512, 512]
    dense_channels: [512, 12]
    pos_embedding: true
    activation: gelu
    normalization: layer
    standardize_latents: True
    self_atten_for_latent: True
    latent_projection_channel: 512
    with_radius: True
    num_blocks: 4
    skeleton_net_config:
      skp_num: 512
      isk_num: 2
      skp_neighbor_num: 32
      radius_scaling: 1.0
      dbscan_eps: 0.65
      dbscan_min_sample_num: 1
  condition_embedding:
    combine_condition: injection
    condition_injection: gate_bias
    encoder:
      name: OneHot
      type: categories
      out_channel: 128
      num_classes: 14
  reconstruction_losses: 
    - name: MSE
loader:
  dataset: 
    name: PcdSDFWithClassLabelDataset
    truncate_sdf: true
    truncate_prob: 0.9
    resolution: 0.022
    data_dir: raw
    data_suffix: .ply
    target_dir: sdf022
    target_suffix: _sdf.npy
    cls_label: MedSDF
  data_path_list: 
    - /data/guoqingzhang/datasets/MedSDF/split/fold1
    - /data/guoqingzhang/datasets/MedSDF/split/fold2
    - /data/guoqingzhang/datasets/MedSDF/split/fold3
    - /data/guoqingzhang/datasets/MedSDF/split/fold4
  batch_size: 4
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: FixedPoints
      method: qfps
      num: 2560
    - name: ToTensor
  target_transforms:
    - name: FixedPoints
      num: 2560
    - name: ToTensor
  class_label_transforms:
    - name: Relabel
      offset: -1
    - name: ToOneHot
      num_classes: 14
    - name: ToTensor
val_split_ratio: 0.1
val_split_seed: 42
## C12: Channel = 12; R: with radius; T: truncate_sdf; TS: scaling truncated SDF to [-1, 1]
## SS: scale and shift; RC: radius constraints
## SKC: skeleton_constraints
check_point_dir: /data/guoqingzhang/vcg-ckp/MedSDF/SkCNN_val_with_la_512/
### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.00000001
### scheduler for learning rate
lr_scheduler: 
  name: LinearLR
  start_factor: 1.0
  end_factor: 0.01
resume: True
max_epoch: 135
write_after_iters: 10
write_sample_num: 4
save_after_epochs: 2
warmup_epochs: 1
warmup_start_scale: 0.01
clip_grad: 1.0
# custom_write_results: [input_sphere, recon_dpm_sphere, gen_sphere]