prediction:
  path: /media/wlsdzyzl/DATA/vcg-results/imageCAS/mesh/SkResCNN_AE_C12_Dilated_Coronary_Condition_NewR_Inter2/left
  suffix: .ply
target:
  path: /media/wlsdzyzl/DATA/datasets/pcd/imageCAS/output_dilated/standardized/rmesh022/left
  suffix: _mesh.ply
eval_type: recon
# eval_batch_num: 2
evaluation_metrics:
    - name: CD