# train ae or vae
#### a template for pcd encoder
mode: test
model:
  # can be AE, VAE, SeM and DDPM
  name: SKNet
  skp_num: 256
  isk_num: 4
  point_num: 5120
  skp_neighbor_num: 72
  radius_scaling: 1.0
  dbscan_eps: 0.65
  dbscan_min_sample_num: 1
loader:
  dataset: 
    name: PcdDataset
    data_dir: raw/coronary_artery_left
    data_suffix: .ply
  data_path_list: 
    - /data/guoqingzhang/datasets/MedSDF/split/fold1
    - /data/guoqingzhang/datasets/MedSDF/split/fold2
    - /data/guoqingzhang/datasets/MedSDF/split/fold3
    - /data/guoqingzhang/datasets/MedSDF/split/fold4
    - /data/guoqingzhang/datasets/MedSDF/split/fold5
  batch_size: 64
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: Normalize
    - name: FixedPoints
      method: qfps
      num: 5120
    - name: ToTensor

custom_save_results: 
  - name: recon_sphere
    dir: /data/guoqingzhang/meshage-results/skeleton/imagecas_surface/sknet/sphere/right
  - name: recon_skeleton
    dir: /data/guoqingzhang/meshage-results/skeleton/imagecas_surface/sknet/skeleton/right
  - name: radius
    dir: /data/guoqingzhang/meshage-results/skeleton/imagecas_surface/sknet/skr/right
# eval_batch_num: 1