# train ae or vae
#### a template for pcd encoder
mode: test
model:
  # can be AE, VAE, SeM and DDPM
  name: SKSDF
  coordinate_sampling_ratio: 0.1
  encoder:
    name: SKSDFCNN
    in_channel: 3
    out_channel: 1
    point_num: 2560
    building_block: res_dense
    projection_channel: 64
    num_neighbors_k_cross: 32
    num_neighbors_k_self: 0
    local_feature_channels: [512, 512, 512, 512]
    seq_feature_channels: [512, 512, 512, 512]
    dense_channels: [512, 12]
    pos_embedding: true
    # voxel_resolutions: [0, 0, 16, 16, 0, 0]
    activation: gelu
    normalization: layer
    standardize_latents: True
    with_radius: True
  reconstruction_losses: 
    - name: MSE
loader:
  dataset: 
    name: PcdSDFDataset
    resolution: 0.022
    data_dir: raw/coronary_artery_left
    data_suffix: .ply
    target_dir: sdf022/coronary_artery_left
    target_suffix: _sdf.npy
    data_path: /media/wlsdzyzl/DATA/datasets/pcd/MedSDF/
  batch_size: 2
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: FixedPoints
      method: qfps
      num: 2560
    - name: ToTensor
  target_transforms:
    - name: ToTensor
pickle_results: True


model_path: /media/wlsdzyzl/DATA/vcg-ckp/coronary_artery_left/SkResCNN_AE_C12_With_RTS25_SS_Rc_wo_Rscaling_fps_2560/ckp_best_loss.pth
recon_dir: /media/wlsdzyzl/DATA/vcg-results/coronary_artery_left/mesh/SkResCNN_AE_C12_With_RTS25_SS_Rc_wo_Rscaling_fps_2560

custom_save_results: 
  - name: latent
    dir: /media/wlsdzyzl/DATA/vcg-results/coronary_artery_left/latent/SkResCNN_AE_C12_With_RTS25_SS_Rc_wo_Rscaling_fps_2560
  - name: skeleton
    dir: /media/wlsdzyzl/DATA/vcg-results/coronary_artery_left/skeleton/SkResCNN_AE_C12_With_RTS25_SS_Rc_wo_Rscaling_fps_2560
# model_path: /media/wlsdzyzl/DATA/vcg-ckp/coronary_artery_left/SkResCNN_AE_C6/ckp_best_loss.pth
# recon_dir: /media/wlsdzyzl/DATA/vcg-results/coronary_artery_left/mesh/SkResCNN_AE_C6

# custom_save_results: 
#   - name: latent
#     dir: /media/wlsdzyzl/DATA/vcg-results/coronary_artery_left/latent/SkResCNN_AE_C6
# eval_batch_num: 4