# train ae or vae
#### a template for pcd encoder
determinstic: true
detect_anomaly: true
mode: train
model:
  # can be AE, VAE, SeM and DDPM
  name: SKSDF
  encoder:
    name: SKSDFCNN
    in_channel: 3
    out_channel: 1
    point_num: 2048
    building_block: dense
    projection_channel: 64
    num_neighbors_k_cross: 20
    num_neighbors_k_self: 0
    local_feature_channels: [64, 128, 256, 512, 512]
    seq_feature_channels: [512, 512, 512]
    dense_channels: [512, 512]
    pos_embedding: true
    # voxel_resolutions: [0, 0, 16, 16, 0, 0]
    activation: gelu
    normalization: layer
  # decoder:
  #   name: SKSDFTrans
  #   building_block: pct_sa
  reconstruction_losses: 
    - name: MSE
loader:
  dataset: 
    name: PcdSDFDataset
    resolution: 0.022
    data_dir: raw/coronary_artery_left
    data_suffix: .ply
    target_dir: sdf022/coronary_artery_left
    target_suffix: _sdf.npy
    data_path: /media/wlsdzyzl/DATA1/datasets/pcd/MedSDF/
  batch_size: 8
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: FixedPoints
      num: 2048
    - name: ToTensor
  target_transforms:
    - name: FixedPoints
      num: 2048
    - name: ToTensor

check_point_dir: /media/wlsdzyzl/DATA1/vcg-ckp/coronary_artery_left/SkCNN_AE/
# resume: true
### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.0001
  weight_decay: 0.00000001
### scheduler for learning rate
lr_scheduler: 
  name: LinearLR
  start_factor: 1.0
  end_factor: 0.01
# resume: True
max_epoch: 100
write_after_iters: 10
write_sample_num: 4
save_after_epochs: 5
warmup_epochs: 1
warmup_start_scale: 0.01
clip_grad: 1.0
# custom_write_results: [input_sphere, recon_dpm_sphere, gen_sphere]