sub_dirs: ['bladder', 'brain', 'colon', 'coronary_artery_left_d', 'coronary_artery_right_d', 'duodenum', 'gallbladder', 'liver', 'pancreas', 'skull', 'spleen', 'stomach', 'trachea', 'uterus']
prediction:
  path: /media/wlsdzyzl/DATA/vcg-results/recon_pcd/DGCNN_AE_FOLDING2
  suffix: .ply
  # transforms: 
  #   - name: FixedPoints
  #     method: qfps
  #     num: 2500
target:
  path: /media/wlsdzyzl/DATA/datasets/pcd/MedSDF/fold5/raw
  suffix: .ply
  data_form: pcd
  transforms: 
    - name: FixedPoints
      method: qfps
      num: 2500
eval_type: recon
# eval_batch_num: 2
evaluation_metrics:
    - name: CD
    - name: EMD
      reg: 1.0
      method: greenkhorn