sub_dirs: ['bladder', 'brain', 'colon', 'coronary_artery_left_d', 'coronary_artery_right_d', 'duodenum', 'gallbladder', 'liver', 'pancreas', 'skull', 'spleen', 'stomach', 'trachea', 'uterus']
prediction:
  path: /home/wlsdzyzl/project/diffusion-point-cloud/results/gen_ply
  suffix: .ply
  transforms: 
    - name: FixedPoints
      method: qfps
      num: 2048
target:
  path: /media/wlsdzyzl/DATA/datasets/pcd/MedSDF/fold5/raw
  suffix: .ply
  data_form: pcd
  transforms: 
    - name: FixedPoints
      method: qfps
      num: 2048
eval_type: gen
# eval_batch_num: 2
evaluation_metrics:
    - name: FID
      embedding_net:
        # can be AE, VAE, SeM and DDPM
        name: ClM
        # encoder config
        encoder:
          name: PointNet
          in_channel: 3
          out_channel: 46
          point_num: 2048
          building_block: dense
          num_neighbors_k: 20
          local_feature_channels: [64, 64, 128, 256, 512]
          dense_channels: [512, 512]
          activation: lrelu
          normalization: group
      embedding_net_path: /media/wlsdzyzl/DATA/flemme-ckp/MedPointS/DGCNN_FOR_FID/ckp_last.pth
      batch_size: 2
    - name: KID
      num_subsets: 10
      subset_size: 50
      embedding_net:
        # can be AE, VAE, SeM and DDPM
        name: ClM
        # encoder config
        encoder:
          name: PointNet
          in_channel: 3
          out_channel: 46
          point_num: 2048
          building_block: dense
          num_neighbors_k: 20
          local_feature_channels: [64, 64, 128, 256, 512]
          dense_channels: [512, 512]
          activation: lrelu
          normalization: group
      embedding_net_path: /media/wlsdzyzl/DATA/flemme-ckp/MedPointS/DGCNN_FOR_FID/ckp_last.pth
      batch_size: 2
    - name: MMDAndCov
      package: loss
      distance: 
        name: CD
    - name: MMDAndCov
      package: loss
      distance:
        name: EMD