sub_dirs: ['bladder', 'brain', 'colon', 'coronary_artery_left_d', 'coronary_artery_right_d', 'duodenum', 'gallbladder', 'liver', 'pancreas', 'skull', 'spleen', 'stomach', 'trachea', 'uterus']
prediction:
  path: /media/wlsdzyzl/DATA/vcg-results/MedSDF/mesh/DGCNN_Recon/
  suffix: .ply
target:
  path: /media/wlsdzyzl/DATA/datasets/pcd/MedSDF/fold5/rmesh022
  suffix: _mesh.ply
eval_type: recon
# eval_batch_num: 2
data_form: pcd
is_mesh: true
evaluation_metrics:
    - name: BettiError