# train ae or vae
#### a template for pcd encoder
mode: test
model:
  # can be AE, VAE, SeM and DDPM
  name: SDF
  coordinate_sampling_ratio: 0.3
  encoder:
    name: SPSDFCNN
    in_channel: 3
    out_channel: 1
    point_num: 2560
    building_block: res_dense
    projection_channel: 64
    num_neighbors_k: 32
    num_fps_points: [1280, 640, 320, 256]
    fps_feature_channels: [512, 512, 512, 512]
    neighbor_radius: [0.2, 0.4, 0.6, 0.8]
    seq_feature_channels: [512, 512, 512, 512]
    dense_channels: [512, 12]
    knn_query: feature
    pos_embedding: true
    activation: gelu
    normalization: layer
    standardize_latents: True
    num_blocks: 4
  condition_embedding:
    combine_condition: injection
    condition_injection: gate_bias
    encoder:
      name: OneHot
      type: categories
      out_channel: 128
      num_classes: 14
  reconstruction_losses: 
    - name: MSE
loader:
  dataset: 
    name: PcdSDFWithClassLabelDataset
    resolution: 0.022
    data_dir: .
    data_suffix: .ply
    target_dir: null
    cls_label: MedSDF
  data_path_list:
    - /media/wlsdzyzl/DATA/vcg-results/recon_pcd/DGCNN_AE_FOLDING2
  batch_size: 1
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: FixedPoints
      num: 2560
    - name: ToTensor
  class_label_transforms:
    - name: Relabel
      offset: -1
    - name: ToOneHot
      num_classes: 14
    - name: ToTensor
## C12: Channel = 12; R: with radius; T: truncate_sdf; TS: scaling truncated SDF to [-1, 1]
## SS: scale and shift; RC: radius constraints
pickle_results: true
model_path: /media/wlsdzyzl/DATA/vcg-ckp/MedSDF/tomesh.pth
recon_dir: /media/wlsdzyzl/DATA/vcg-results/MedSDF/mesh/DGCNN_Recon/
