prediction:
  path: /data/guoqingzhang/vcg-results/imageCAS_vessel_diff/mesh/VessDiff
  suffix: _4096.ply

target:
  path: /data/guoqingzhang/datasets/imageCAS/fold5/rmesh022
  suffix: _mesh.ply
eval_type: recon
# eval_batch_num: 2
data_form: pcd
is_mesh: true
evaluation_metrics:
    - name: BettiError
      min_num_faces: 100
      min_hole_size: 50