# train ae or vae
#### a template for pcd encoder
mode: test
model:
  # can be AE, VAE, SeM and DDPM
  name: LDM
  diffusion:
    name: EDM
    # classifier_free_guidance:
    #   condition_dropout: 0.2
    #   guidance_weight: 2.0
    eps_model:
      time_channel: 128
      encoder:
        name: SeqTrans
        in_channel: 16
        point_num: 400
        building_block: pct_sa
        seq_feature_channels: [512, 512, 512, 512, 512, 512]
        num_heads: 8
        d_k: 64
        activation: gelu
        normalization: layer
    eps_loss:
      name: MSE
  autoencoder:
    name: SDF
    coordinate_sampling_ratio: 0.1
    encoder:
      name: SKSDFCNN
      in_channel: 3
      out_channel: 1
      point_num: 4096
      building_block: res_dense
      projection_channel: 64
      num_neighbors_k_cross: 32
      num_neighbors_k_self: 0
      local_feature_channels: [512, 512, 512, 512]
      seq_feature_channels: [512, 512, 512, 512]
      dense_channels: [512, 12]
      pos_embedding: true
      # voxel_resolutions: [0, 0, 16, 16, 0, 0]
      activation: gelu
      normalization: layer
      standardize_latents: True
      with_radius: True
      skeleton_net_config:
        skp_num: 400
        isk_num: 2
        skp_neighbor_num: 32
        radius_scaling: 1.0
        dbscan_eps: 0.65
        dbscan_min_sample_num: 1
    reconstruction_losses: 
      - name: MSE
    
model_path:
  diff_model: /media/wlsdzyzl/DATA/vcg-ckp/imageCAS_vessel_diff/SeqTrans_SkCNN_with_SKC/ckp_last.pth
  ae_model: /media/wlsdzyzl/DATA/vcg-ckp/imageCAS_vessel_diff/SkCNN_val_with_SKC/ckp_best_loss.pth
eval_gen:
  sampler:
    name: NormalSampler
    batch_size: 2
  gen_dir: /media/wlsdzyzl/DATA/vcg-results/imageCAS_vessel_diff/gen/LDM_EDM_SkCNN_with_SKC/
  ### new generation from random noise
  random_sample_num: 500
