# train ae or vae
#### a template for pcd encoder
mode: train
model:
  # can be AE, VAE, SeM and DDPM
  name: EDM
  eps_model:
    time_channel: 128
    encoder:
      name: SeqTrans
      in_channel: 16
      point_num: 400
      building_block: pct_sa
      seq_feature_channels: [512, 512, 512, 512, 512, 512]
      num_heads: 8
      d_k: 64
      activation: gelu
      normalization: layer
  eps_loss:
    name: MSE
loader:
  dataset: 
    name: PcdDataset
    data_suffix: .npy
  data_path_list: 
    - /data/guoqingzhang/meshage-results/imageCAS_vessel_diff/latent/SkCNN_val_for_train
  batch_size: 8
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: ToTensor

check_point_dir: /data/guoqingzhang/meshage-ckp/imageCAS_vessel_diff/SeqTrans_SkCNN
resume: True
### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.001
  weight_decay: 0.00000001
### scheduler for learning rate
lr_scheduler: 
  name: LinearLR
  start_factor: 1.0
  end_factor: 0.01
sampler:
  name: NormalSampler
max_epoch: 1000
write_after_iters: 10
write_sample_num: 4
save_after_epochs: 10
warmup_epochs: 1
warmup_start_scale: 0.01
clip_grad: 1.0
