sub_dirs: ['bladder', 'brain', 'colon', 'coronary_artery_left_d', 'coronary_artery_right_d', 'duodenum', 'gallbladder', 'liver', 'pancreas', 'skull', 'spleen', 'stomach', 'trachea', 'uterus']
prediction:
  # path: /data/guoqingzhang/GEM3D_paper_code/MedSDF/reconstruction_re90_mcubes/shapenet_skelnet_skelrays_reg_skelrays_min_sdf_iter_50_1000rays_random_reg_abs_loss_8_heads__p2p_vecset_skeletons_min_sdf_iter_50_p2p_min_sdf_vecset__ball_recon__2__res_90__2048/recon
  path: /data/guoqingzhang/meshage-results/MedSDF/gen/GeM3D_origin
  suffix: .ply
  transforms: 
    - name: FixedPoints
      method: qfps
      num: 2048
    - name: Normalize

target:
  path: /data/guoqingzhang/datasets/MedSDF/split/fold5/raw
  suffix: .ply
  transforms: 
    - name: FixedPoints
      method: qfps
      num: 2048
    - name: Normalize
eval_type: gen
data_form: pcd
evaluation_metrics:
    - name: FID
      embedding_net:
        # can be AE, VAE, SeM and DDPM
        name: ClM
        # encoder config
        encoder:
          name: PointNet
          in_channel: 3
          out_channel: 46
          point_num: 2048
          building_block: dense
          num_neighbors_k: 20
          local_feature_channels: [64, 64, 128, 256, 512]
          dense_channels: [512, 512]
          activation: lrelu
          normalization: group
      embedding_net_path: /data/guoqingzhang/flemme-ckp/MedPointS/DGCNN_FOR_FID/ckp_last.pth
      batch_size: 2
    - name: KID
      num_subsets: 10
      subset_size: 50
      embedding_net:
        # can be AE, VAE, SeM and DDPM
        name: ClM
        # encoder config
        encoder:
          name: PointNet
          in_channel: 3
          out_channel: 46
          point_num: 2048
          building_block: dense
          num_neighbors_k: 20
          local_feature_channels: [64, 64, 128, 256, 512]
          dense_channels: [512, 512]
          activation: lrelu
          normalization: group
      embedding_net_path: /data/guoqingzhang/flemme-ckp/MedPointS/DGCNN_FOR_FID/ckp_last.pth
      batch_size: 2
    - name: MMD&Cov
      package: loss
      distance: 
        name: CD
    - name: MMD&Cov
      package: loss
      distance:
        name: EMD