sub_dirs: ['bladder', 'brain', 'colon', 'coronary_artery_left_d', 'coronary_artery_right_d', 'duodenum', 'gallbladder', 'liver', 'pancreas', 'skull', 'spleen', 'stomach', 'trachea', 'uterus']
prediction:
  path: /data/guoqingzhang/meshage-results/MedSDF/mesh/PointMamba2/
  suffix: .ply
target:
  path: /data/guoqingzhang/datasets/MedSDF/split/fold5/rmesh022
  suffix: _mesh.ply
eval_type: recon
data_form: pcd
is_mesh: true
evaluation_metrics:
    - name: BettiError
      min_num_faces: 100
      min_hole_size: 50
      # method: simplex