sub_dirs: ['bladder', 'brain', 'colon', 'coronary_artery_left_d', 'coronary_artery_right_d', 'duodenum', 'gallbladder', 'liver', 'pancreas', 'skull', 'spleen', 'stomach', 'trachea', 'uterus']
prediction:
  path: /data/guoqingzhang/vcg-results/MedSDF/gen/PVD_Mesh
  suffix: .ply
target:
  path: /data/guoqingzhang/datasets/MedSDF/split/fold5/rmesh022
  suffix: .ply
eval_type: gen
# eval_batch_num: 2
is_mesh: true
data_form: pcd
evaluation_metrics:
    - name: meanBettiError
      min_num_faces: 100
      min_hole_size: 50