# train ae or vae
#### a template for pcd encoder
mode: test
model:
  # can be AE, VAE, SeM and DDPM
  name: AE
  encoder:
    name: PointTrans2
    in_channel: 3
    out_channel: 3
    point_num: 2560
    projection_channel: 64
    num_neighbors_k: 32
    building_block: pct_oa
    num_fps_points: [1280, 640, 320, 160]
    fps_feature_channels: [512, 512, 512, 512]
    # neighbor_radius: [0.2, 0.4, 0.6, 0.8]
    dense_channels: [1024, 1024]
    activation: lrelu
    normalization: group
    knn_query: feature
    pos_embedding: True
    vector_embedding: True
    num_blocks: 2
  decoder:
    name: PointNet
    folding_times: 2
  condition_embedding:
    combine_condition: injection
    condition_injection: gate_bias
    encoder:
      name: OneHot
      type: categories
      out_channel: 128
      num_classes: 14
  reconstruction_losses: 
    - name: DCD
      alpha: 40
      n_lambda: 0.5
    - name: CD
      weight: 0.001
loader:
  dataset: 
    name: PcdClsDataset
    data_suffix: _mesh.ply
    target_dir: sdf022
    target_suffix: _sdf.npy
    cls_label: MedSDF
  data_path_list: 
    - /data/guoqingzhang/datasets/MedSDF/split/fold5/rmesh022
  batch_size: 4
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: FixedPoints
      method: qfps
      num: 2560
    - name: ToTensor
  target_transforms:
    - name: FixedPoints
      num: 2560
    - name: ToTensor
  class_label_transforms:
    - name: Relabel
      offset: -1
    - name: ToOneHot
      num_classes: 14
    - name: ToTensor
## C12: Channel = 12; R: with radius; T: truncate_sdf; TS: scaling truncated SDF to [-1, 1]
## SS: scale and shift; RC: radius constraints

pickle_results: True
pickle_path: /data/guoqingzhang/meshage-pickle
model_path: /data/guoqingzhang/meshage-ckp/MedSDF/PCT2_AE_FOLDING2/ckp_best_loss.pth
recon_dir: /data/guoqingzhang/meshage-results/MedSDF/recon_pcd/PCT2_AE_FOLDING2
