# train ae or vae
#### a template for pcd encoder
mode: train
model:
  # can be AE, VAE, SeM and DDPM
  name: EDM
  classifier_free_guidance:
    condition_dropout: 0.2
    guidance_weight: 2.0
  eps_model:
    time_channel: 128
    encoder:
      name: PointNet2
      in_channel: 3
      point_num: 2560
      building_block: res_dense
      num_neighbors_k: 32
      num_fps_points: [1280, 640, 320, 160]
      fps_feature_channels: [512, 512, 512, 512]
      voxel_resolutions: [32, 32, 16, 16]
      voxel_attens: [null, null, atten, atten]
      # neighbor_radius: [0.2, 0.4, 0.6, 0.8]
      dense_channels: [1024, 1024]
      activation: silu
      normalization: group
      num_blocks: 2
      # vector_embedding: false
    condition_embedding:
      combine_condition: injection
      condition_injection: gate_bias
      encoder:
        name: OneHot
        type: categories
        out_channel: 128
        num_classes: 14
      decoder: same_as_encoder
  eps_loss:
    name: MSE
loader:
  dataset: 
    name: PcdClsDataset
    data_suffix: .ply
    cls_label: MedSDF
  data_path_list: 
    - /data/guoqingzhang/datasets/MedSDF/split/fold1/raw
    - /data/guoqingzhang/datasets/MedSDF/split/fold2/raw
    - /data/guoqingzhang/datasets/MedSDF/split/fold3/raw
    - /data/guoqingzhang/datasets/MedSDF/split/fold4/raw
  batch_size: 8
  num_workers: 8
  shuffle: true
  data_transforms:
    - name: FixedPoints
      method: qfps
      num: 2560
    - name: ToTensor
  class_label_transforms:
    - name: Relabel
      offset: -1
    - name: ToOneHot
      num_classes: 14
    - name: ToTensor  
val_split_ratio: 0.1
val_split_seed: 42
check_point_dir: /data/guoqingzhang/meshage-ckp/MedSDF/PVD
resume: True
### parameter for optimizer
optimizer:
  name: Adam
  lr: 0.001
  weight_decay: 0.00000001
### scheduler for learning rate
lr_scheduler: 
  name: LinearLR
  start_factor: 1.0
  end_factor: 0.01
sampler:
  name: NormalSampler
max_epoch: 100
write_after_iters: 10
write_sample_num: 4
save_after_epochs: 10
warmup_epochs: 1
warmup_start_scale: 0.01
clip_grad: 1.0
