#!/bin/bash
python generate_sdf_from_skeleton.py --surface_dir /media/wlsdzyzl/DATA1/datasets/pcd/imageCAS/output_lr/surface --skeleton_dir /media/wlsdzyzl/DATA1/datasets/pcd/imageCAS/output_lr/skeleton --sdf_dir /media/wlsdzyzl/DATA1/datasets/pcd/imageCAS/output_lr/sdf --recon_mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/imageCAS/output_lr/mesh_from_sdf --sdf_smoothing --num_nn 5  --resume
python generate_sdf_from_mesh.py --mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet/liver --mesh_suffix .stl --sdf_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet_SDF/liver --recon_mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet_Mesh_New/liver --mesh_smoothing --sdf_smoothing --normalization --resume
python generate_sdf_from_mesh.py --mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet/bladder --mesh_suffix .stl --sdf_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet_SDF/bladder --recon_mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet_Mesh_New/bladder --mesh_smoothing --sdf_smoothing --normalization
python generate_sdf_from_mesh.py --mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet/gallbladder --mesh_suffix .stl --sdf_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet_SDF/gallbladder --recon_mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet_Mesh_New/gallbladder --mesh_smoothing --sdf_smoothing --normalization
python generate_sdf_from_mesh.py --mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet/duodenum --mesh_suffix .stl --sdf_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet_SDF/duodenum --recon_mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet_Mesh_New/duodenum --mesh_smoothing --sdf_smoothing --normalization
python generate_sdf_from_mesh.py --mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet/brain --mesh_suffix .stl --sdf_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet_SDF/brain --recon_mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet_Mesh_New/brain --mesh_smoothing --sdf_smoothing --normalization
python generate_sdf_from_mesh.py --mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet/spleen --mesh_suffix .stl --sdf_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet_SDF/spleen --recon_mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet_Mesh_New/spleen --mesh_smoothing --sdf_smoothing --normalization
python generate_sdf_from_mesh.py --mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet/stomach --mesh_suffix .stl --sdf_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet_SDF/stomach --recon_mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet_Mesh_New/stomach --mesh_smoothing --sdf_smoothing --normalization
python generate_sdf_from_mesh.py --mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet/uterus --mesh_suffix .stl --sdf_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet_SDF/uterus --recon_mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet_Mesh_New/uterus --mesh_smoothing --sdf_smoothing --normalization
python generate_sdf_from_mesh.py --mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet/trachea --mesh_suffix .stl --sdf_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet_SDF/trachea --recon_mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet_Mesh_New/trachea --mesh_smoothing --sdf_smoothing --normalization
python generate_sdf_from_mesh.py --mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet/pancreas --mesh_suffix .stl --sdf_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet_SDF/pancreas --recon_mesh_dir /media/wlsdzyzl/DATA1/datasets/pcd/MedShapeNet_Mesh_New/pancreas --mesh_smoothing --sdf_smoothing --normalization