#!/bin/bash
# generate sdf with low resolution

# python generate_sdf_from_sdf.py --input_dir /media/wlsdzyzl/DATA/datasets/pcd/MedSDF/001/sdf/coronary_artery_left --sdf_dir /media/wlsdzyzl/DATA/datasets/pcd/MedShapeNet_SDF/coronary_artery_left --recon_mesh_dir /media/wlsdzyzl/DATA/datasets/pcd/MedShapeNet_Mesh/coronary_artery_left --sdf_smoothing --resolution 0.022 --resume
# python generate_sdf_from_sdf.py --input_dir /media/wlsdzyzl/DATA/datasets/pcd/MedSDF/001/sdf/coronary_artery_right --sdf_dir /media/wlsdzyzl/DATA/datasets/pcd/MedShapeNet_SDF/coronary_artery_right --recon_mesh_dir /media/wlsdzyzl/DATA/datasets/pcd/MedShapeNet_Mesh/coronary_artery_right --sdf_smoothing --resolution 0.022 --resume
# python generate_sdf_from_sdf.py --input_dir /media/wlsdzyzl/DATA/datasets/pcd/MedSDF/001/sdf/liver --sdf_dir /media/wlsdzyzl/DATA/datasets/pcd/MedShapeNet_SDF/liver --recon_mesh_dir /media/wlsdzyzl/DATA/datasets/pcd/MedShapeNet_Mesh/liver --sdf_smoothing --resolution 0.022 --resume
# python generate_sdf_from_sdf.py --input_dir /media/wlsdzyzl/DATA/datasets/pcd/MedSDF/001/sdf/bladder --sdf_dir /media/wlsdzyzl/DATA/datasets/pcd/MedShapeNet_SDF/bladder --recon_mesh_dir /media/wlsdzyzl/DATA/datasets/pcd/MedShapeNet_Mesh/bladder --sdf_smoothing --resolution 0.022 --resume
# python generate_sdf_from_sdf.py --input_dir /media/wlsdzyzl/DATA/datasets/pcd/MedSDF/001/sdf/gallbladder --sdf_dir /media/wlsdzyzl/DATA/datasets/pcd/MedShapeNet_SDF/gallbladder --recon_mesh_dir /media/wlsdzyzl/DATA/datasets/pcd/MedShapeNet_Mesh/gallbladder --sdf_smoothing --resolution 0.022 --resume
# python generate_sdf_from_sdf.py --input_dir /media/wlsdzyzl/DATA/datasets/pcd/MedSDF/001/sdf/duodenum --sdf_dir /home/wlsdzyzl/MedShapeNet_SDF/duodenum --recon_mesh_dir /home/wlsdzyzl/MedShapeNet_Mesh/duodenum --sdf_smoothing --resolution 0.022 --resume
# python generate_sdf_from_sdf.py --input_dir /media/wlsdzyzl/DATA/datasets/pcd/MedSDF/001/sdf/brain --sdf_dir /home/wlsdzyzl/MedShapeNet_SDF/brain --recon_mesh_dir /home/wlsdzyzl/MedShapeNet_Mesh/brain --sdf_smoothing --resolution 0.022 --resume
# python generate_sdf_from_sdf.py --input_dir /media/wlsdzyzl/DATA/datasets/pcd/MedSDF/001/sdf/spleen --sdf_dir /home/wlsdzyzl/MedShapeNet_SDF/spleen --recon_mesh_dir /home/wlsdzyzl/MedShapeNet_Mesh/spleen --sdf_smoothing --resolution 0.022 --resume
# python generate_sdf_from_sdf.py --input_dir /media/wlsdzyzl/DATA/datasets/pcd/MedSDF/001/sdf/stomach --sdf_dir /home/wlsdzyzl/MedShapeNet_SDF/stomach --recon_mesh_dir /home/wlsdzyzl/MedShapeNet_Mesh/stomach --sdf_smoothing --resolution 0.022 --resume
# python generate_sdf_from_sdf.py --input_dir /media/wlsdzyzl/DATA/datasets/pcd/MedSDF/001/sdf/uterus --sdf_dir /home/wlsdzyzl/MedShapeNet_SDF/uterus --recon_mesh_dir /home/wlsdzyzl/MedShapeNet_Mesh/uterus --sdf_smoothing --resolution 0.022 --resume
# python generate_sdf_from_sdf.py --input_dir /media/wlsdzyzl/DATA/datasets/pcd/MedSDF/001/sdf/trachea --sdf_dir /home/wlsdzyzl/MedShapeNet_SDF/trachea --recon_mesh_dir /home/wlsdzyzl/MedShapeNet_Mesh/trachea --sdf_smoothing --resolution 0.022 --resume
# python generate_sdf_from_sdf.py --input_dir /media/wlsdzyzl/DATA/datasets/pcd/MedSDF/001/sdf/pancreas --sdf_dir /home/wlsdzyzl/MedShapeNet_SDF/pancreas --recon_mesh_dir /home/wlsdzyzl/MedShapeNet_Mesh/pancreas --sdf_smoothing --resolution 0.022 --resume
python generate_sdf_from_sdf.py --input_dir /media/wlsdzyzl/DATA/datasets/pcd/MedSDF/001/sdf/colon --sdf_dir /media/wlsdzyzl/DATA/datasets/pcd/MedShapeNet_SDF/colon --recon_mesh_dir /media/wlsdzyzl/DATA/datasets/pcd/MedShapeNet_Mesh/colon --sdf_smoothing --resolution 0.022 --resume
python generate_sdf_from_sdf.py --input_dir /media/wlsdzyzl/DATA/datasets/pcd/MedSDF/001/sdf/skull --sdf_dir /media/wlsdzyzl/DATA/datasets/pcd/MedShapeNet_SDF/skull --recon_mesh_dir /media/wlsdzyzl/DATA/datasets/pcd/MedShapeNet_Mesh/skull --sdf_smoothing --resolution 0.022 --resume