prediction:
  path: /data/guoqingzhang/meshage-results/CoW_vessel_diff/gen/LDM_EDM_SkCNN_with_SKC_LA
  suffix: .ply
target:
  path: /data/guoqingzhang/datasets/CoW/fold5/rmesh022
  suffix: .ply
eval_type: gen
# eval_batch_num: 2
data_form: pcd
is_mesh: true
evaluation_metrics:
    - name: meanBettiError
      min_num_faces: 100
      min_hole_size: 50